NDefines.NGame.MAX_TRADING_CITIES = 15

NDefines.NCountry.EXPLOIT_ADM_INCOME = 30
NDefines.NCountry.EXPLOIT_DIP_SAILORS = 3
NDefines.NCountry.EXPLOIT_MIL_MANPOWER = 3
NDefines.NCountry.EXPLOIT_COOLDOWN_MONTHS = 60
NDefines.NCountry.PS_IMPROVE_PROVINCE_BASE = 25
NDefines.NCountry.SPLENDOR_ABILITY_COST = 1000
NDefines.NCountry.MAXIMUM_ADVISOR_SKILL = 10
NDefines.NCountry.LAND_FORCELIMIT_EXTRA_COST_FACTOR = 3
NDefines.NCountry.NAVAL_FORCELIMIT_EXTRA_COST_FACTOR = 3

NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0

NDefines.NReligion.AUTHORITY_FROM_DEVELOPMENT = 0.04
NDefines.NReligion.PIETY_MANPOWER = 0.5

NDefines.NMilitary.CREATE_HUSSARS_MIL_COST = 5

NDefines.NEconomy.INFLATION_FROM_LOAN = 0.15
NDefines.NEconomy.DEBASE_MAX_CORRUPTION = 20
NDefines.NEconomy.MINIMUM_INTERESTS = 2.0
NDefines.NEconomy.BANKRUPTCY_BUILDING_DESTRUCTION_THRESHOLD = 10